"""empty message

Revision ID: 820d27e04c49
Revises: 
Create Date: 2020-02-07 18:32:24.571289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820d27e04c49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('PA_TOKEN', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PA_TOKEN'),
    sa.UniqueConstraint('bot_id'),
    sa.UniqueConstraint('page_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('progress_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('last_message', sa.String(), nullable=True),
    sa.Column('last_date', sa.BigInteger(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('combine', sa.Boolean(), nullable=True),
    sa.Column('chatbot_message_delivered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_table('user')
    op.drop_table('page_access')
    # ### end Alembic commands ###
